/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uy.com.utu.gui;

import uy.com.utu.dto.SociosAll;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import uy.com.utu.business.SociosallBus;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import uy.com.utu.cone.sql.ConectaDB;
import javax.swing.JOptionPane;

/**
 *
 * @author jose
 */
public class FormEditarSocios extends javax.swing.JFrame {

    public SociosallBus sociosBus;
    public List<SociosAll> list;
    public SociosAll sociosall;

    DefaultTableModel modelo;

    public boolean option = false;

    /**
     * Creates new form FormEditarSocios
     */
    public FormEditarSocios() throws SQLException {
        initComponents();
        setLocationRelativeTo(null);
        this.setTitle("Ingreso de Nuevo Socio");
        sociosall = new SociosAll();
        list = new ArrayList<SociosAll>();
         caragarSocios();
        buscarSocios(1);
        LoadSelectPlan();
        LaodSexo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtnombre = new javax.swing.JTextPane();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtapellido = new javax.swing.JTextPane();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtci = new javax.swing.JTextPane();
        comboboxsexo = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtdireccion = new javax.swing.JTextPane();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        txttel = new javax.swing.JTextPane();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtmovil = new javax.swing.JTextPane();
        combofuncionario = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        comboboxplan = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        comboactividades = new javax.swing.JComboBox();
        jScrollPane8 = new javax.swing.JScrollPane();
        txtfechanacimiento = new javax.swing.JTextPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablesocios = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        txtidsocio = new javax.swing.JTextPane();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("/home/jose/Imágenes/Imagenes Java/socios_insettitle.png")); // NOI18N
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 58));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uy/com/utu/gui/icono_nuevo.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uy/com/utu/gui/icono_save.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uy/com/utu/gui/icono_edit.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, -1, -1));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uy/com/utu/gui/icono_close.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uy/com/utu/gui/icono_close_1.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, -1, -1));

        jLabel3.setText("Nombre ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 70, 20));

        jScrollPane2.setViewportView(txtnombre);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 330, -1));

        jLabel4.setText("Apellido");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, 20));

        jScrollPane3.setViewportView(txtapellido);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 280, -1));

        jLabel5.setText("Edad");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 80, 20));

        jLabel6.setText("Ci");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 40, 20));

        jScrollPane4.setViewportView(txtci);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 280, -1));

        getContentPane().add(comboboxsexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 220, 30));

        jLabel7.setText("Sexo");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, -1, 20));

        jLabel8.setText("Dirección");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, 30));

        jScrollPane5.setViewportView(txtdireccion);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 280, -1));

        jLabel9.setText("Tel");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 70, 20));

        jScrollPane6.setViewportView(txttel);

        getContentPane().add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, 220, -1));

        jLabel10.setText("Móvil");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 60, 30));

        jScrollPane7.setViewportView(txtmovil);

        getContentPane().add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 280, -1));

        combofuncionario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No", "Si" }));
        getContentPane().add(combofuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 280, 220, -1));

        jLabel11.setText("Funcionario");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, 90, 20));

        jLabel13.setText("Plan");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 60, 20));

        comboboxplan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxplanActionPerformed(evt);
            }
        });
        getContentPane().add(comboboxplan, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 280, -1));

        jLabel15.setText("Actividades");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, -1, 40));

        comboactividades.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No", "Si" }));
        comboactividades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboactividadesActionPerformed(evt);
            }
        });
        getContentPane().add(comboactividades, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 320, 220, -1));

        jScrollPane8.setViewportView(txtfechanacimiento);

        getContentPane().add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, 130, -1));

        tablesocios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablesocios);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 680, 310));

        jLabel2.setText("Id");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        txtidsocio.setEnabled(false);
        jScrollPane9.setViewportView(txtidsocio);

        getContentPane().add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 100, -1));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uy/com/utu/gui/icono_search.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 60, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       limpiarCampos();
       codSocios();
       option=true;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      if(option==true){
         insertSocios();
      }  else{
          ActualizarSocios();
      } 
      
      caragarSocios();

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
     option=false;
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
         EliminarSocios();
         caragarSocios();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void comboactividadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboactividadesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboactividadesActionPerformed

    private void comboboxplanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxplanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboboxplanActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Integer id = Integer.valueOf(JOptionPane.showInputDialog("Ingrese Código de Socio"));
        buscarSocios(id);
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormEditarSocios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormEditarSocios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormEditarSocios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormEditarSocios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FormEditarSocios().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(FormEditarSocios.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox comboactividades;
    private javax.swing.JComboBox comboboxplan;
    private javax.swing.JComboBox comboboxsexo;
    private javax.swing.JComboBox combofuncionario;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTable tablesocios;
    private javax.swing.JTextPane txtapellido;
    private javax.swing.JTextPane txtci;
    private javax.swing.JTextPane txtdireccion;
    private javax.swing.JTextPane txtfechanacimiento;
    private javax.swing.JTextPane txtidsocio;
    private javax.swing.JTextPane txtmovil;
    private javax.swing.JTextPane txtnombre;
    private javax.swing.JTextPane txttel;
    // End of variables declaration//GEN-END:variables

    private void LoadSelectPlan() throws SQLException {
        ConectaDB con = new ConectaDB();
        Connection conn = con.getConnection();
        ResultSet rs;
        String sql = "SELECT NAME FROM CONFIGURATION_ACTIVITY";
        PreparedStatement sqls = conn.prepareStatement(sql);
        rs = sqls.executeQuery();
        while (rs.next()) {
            this.comboboxplan.addItem(rs.getString("NAME"));
        }
    }

    private void LaodSexo() throws SQLException {
        ConectaDB con = new ConectaDB();
        Connection conn = con.getConnection();
        ResultSet rs;
        String sql = "SELECT NAME_SEXO FROM SEXO";
        PreparedStatement sqls = conn.prepareStatement(sql);
        rs = sqls.executeQuery();
        while (rs.next()) {
            this.comboboxsexo.addItem(rs.getString("NAME_SEXO"));
        }
    }

    private final void caragarSocios() {
       try{
        String[] title = {"Nombre", "Apellido", "Dirección", "Teléfono", "Cel"};
        modelo = new DefaultTableModel(null, title);
        String[] row = new String[5];
        list = sociosBus.list();
        for (SociosAll s : list) {
            row[0] = String.valueOf(s.getNameSocio());
            row[1] = String.valueOf(s.getLastNameSocio());
            row[2] = String.valueOf(s.getAddress());
            row[3] = String.valueOf(s.getPhone());
            row[4] = String.valueOf(s.getMovile());
            modelo.addRow(row);

        }

        tablesocios.setModel(modelo);
       }catch(Exception e){
           
       }
    }

    public void asingnarSocios() {

        sociosall = new SociosAll();

        String selecionadoplan = (String) comboboxplan.getSelectedItem();
        String seleccionarsexo = (String) comboboxsexo.getSelectedItem();
        String funcionario = (String) combofuncionario.getSelectedItem();
        String participa = (String) comboactividades.getSelectedItem();

        Integer idplan = 0;
        Integer idsexo = 0;

        try {

            idplan = ReturnIdplan(selecionadoplan);
            idsexo = ReturnIdSexo(seleccionarsexo);

            sociosall.setNameSocio(txtnombre.getText());
            sociosall.setLastNameSocio(txtapellido.getText());
            sociosall.setAge(Integer.parseInt(txtfechanacimiento.getText()));
            sociosall.setCI(txtci.getText());
            sociosall.setIdSexo(idsexo);
            sociosall.setAddress(txtdireccion.getText());
            sociosall.setPhone(txttel.getText());
            sociosall.setMovile(txtmovil.getText());
            sociosall.setType(funcionario);
            sociosall.setIdPlan(idplan);
            sociosall.setActivity(participa);

        } catch (SQLException ex) {
            Logger.getLogger(ActivitiesTimetable.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void insertSocios() {
        String rpta;
        asingnarSocios();
        rpta = sociosBus.insertSociosall(sociosall);
        if (rpta == null) {
            JOptionPane.showMessageDialog(null, "Se Ingresaron los datos correctamente");
        } else {
            JOptionPane.showMessageDialog(null, "Error al ingresar los datos");
        }
    }

    public void codSocios() {
        Integer id = sociosBus.idSociosall();
        txtidsocio.setText(String.valueOf(id));
    }

    private void buscarSocios(Integer id) {
        try{
        sociosall = sociosBus.get(id);
        if (sociosall.getIdSocio() != null) {
            txtidsocio.setText(String.valueOf(sociosall.getIdSocio()));
            txtnombre.setText(sociosall.getNameSocio());
            txtapellido.setText(sociosall.getLastNameSocio());
            txtfechanacimiento.setText(String.valueOf(sociosall.getAge()));
            txtci.setText(sociosall.getCI());
            txtdireccion.setText(sociosall.getAddress());
            txttel.setText(sociosall.getPhone());
            txtmovil.setText(sociosall.getMovile());

        } else {
            JOptionPane.showMessageDialog(null, "Error al cargar los datos");
        }
        }catch(Exception e){
          JOptionPane.showMessageDialog(null, "Error al cargar los datos" + e.getMessage());
        }
    }

    public void EliminarSocios() {
        try {
            Integer id = Integer.parseInt(txtidsocio.getText());
            String rpta = sociosBus.delete(id);
            if (rpta == null) {
                JOptionPane.showMessageDialog(null, "Datos eliminados correctamente");
            } else {
                JOptionPane.showMessageDialog(null, "Error al eliminar los datos " + rpta);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al eliminar los datos " + e);
        }

    }

    public void ActualizarSocios() {
        try {
            asingnarSocios();
            String rpta = sociosBus.update(sociosall);
            if (null != rpta) {
                JOptionPane.showMessageDialog(null, "Error al actualizar los datos" + rpta);
            } else {
                JOptionPane.showMessageDialog(null, "Datos Actualizados corerctamente");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al actualizar los datos " + e);
        }
    }
    
    public void limpiarCampos(){
        txtidsocio.setText(null);
        txtnombre.setText(null);
        txtfechanacimiento.setText(null);
        txtci.setText(null);
        txtdireccion.setText(null);
        txttel.setText(null);
        txtmovil.setText(null);
        
    }

    private Integer ReturnIdplan(String selecionado) throws SQLException {
        ConectaDB con = new ConectaDB();
        Connection conn = con.getConnection();
        ResultSet rs;
        String sql = "SELECT ID FROM CONFIGURATION_ACTIVITY WHERE NAME=?";
        PreparedStatement sqls = conn.prepareStatement(sql);
        sqls.setString(1, selecionado);
        rs = sqls.executeQuery();
        Integer ret_id = 0;
        while (rs.next()) {
            ret_id = rs.getInt("ID");
        }
        return ret_id;
    }

    private Integer ReturnIdSexo(String selecionoIdSexo) throws SQLException {
        ConectaDB con = new ConectaDB();
        Connection conn = con.getConnection();
        ResultSet rs;

        String sql = "SELECT ID_SEXO FROM SEXO WHERE NAME_SEXO=?";
        PreparedStatement sqls = conn.prepareStatement(sql);
        sqls.setString(1, selecionoIdSexo);
        rs = sqls.executeQuery();
        Integer idSexo = 0;
        while (rs.next()) {
            idSexo = rs.getInt("ID_SEXO");
        }

        return idSexo;

    }
}
