/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package uy.com.utu.gui;

import uy.com.utu.dto.ConfigurationActivity;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import uy.com.utu.business.ConfigurationActivityBus;

/**
 *
 * @author jose
 */
public class FormListadoConfAct extends javax.swing.JFrame {
   public ConfigurationActivityBus actconfbus;
   public List<ConfigurationActivity>list;
   public ConfigurationActivity actconf;
   
   DefaultTableModel modelo;
    /**
     * Creates new form FormListadoConfAct
     */
    public FormListadoConfAct() {
        initComponents();
        setLocationRelativeTo(null);
        this.setTitle("Listado de Actividades Activas");
        actconfbus= new ConfigurationActivityBus();
        list=new ArrayList<ConfigurationActivity>();
        loadtablelist();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablelistact = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("/home/jose/Imágenes/Imagenes Java/listado_de_planes.png")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 695, 52));

        tablelistact.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablelistact);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 690, 420));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uy/com/utu/gui/icono_close_1.png"))); // NOI18N
        jButton2.setText("Salir");
        jButton2.setToolTipText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 490, 120, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormListadoConfAct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormListadoConfAct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormListadoConfAct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormListadoConfAct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormListadoConfAct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablelistact;
    // End of variables declaration//GEN-END:variables

    private void loadtablelist() {
       String[] titles={"Plan","Hora Comienzo", "Hora Fin","Lunes","Martes","Miercoles","Juves","Viernes","Sabado","Precio"};
       modelo = new DefaultTableModel(null, titles);
       String[] row = new String[11];
       list=actconfbus.list();
       
       for(ConfigurationActivity conf : list){
           row[0]=String.valueOf(conf.getNameconf());
           row[1]=String.valueOf(conf.getFrom_time());
           row[2]=String.valueOf(conf.getTime_to());
           row[3]=String.valueOf(conf.getMonday());
           row[4]=String.valueOf(conf.getTuesday());
           row[5]=String.valueOf(conf.getWednsesday());
           row[6]=String.valueOf(conf.getThursday());
           row[7]=String.valueOf(conf.getFriday());
           row[8]=String.valueOf(conf.getSaterday());
           row[9]=String.valueOf(conf.getPrice());
           modelo.addRow(row);
       }
       tablelistact.setModel(modelo);
    }
}
