/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uy.com.utu.gui;

import java.awt.HeadlessException;
import java.util.ArrayList;
import uy.com.utu.dto.ConfigurationGim;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import uy.com.utu.business.ConfigGymBus;

/**
 *
 * @author jose
 */
public class FormLocationActivity extends javax.swing.JFrame {

    public ConfigGymBus ConGymBus;
    public List<ConfigurationGim> list;
    public ConfigurationGim configurationGim;

    DefaultTableModel modelo;

    /*
     Valor para manejar opciones
     */
    public boolean option = false;

    /**
     * Creates new form FormLocationActivity
     */
    public FormLocationActivity() {
        initComponents();
        setLocationRelativeTo(null);
        this.setTitle("Configuración de Gimnasio y Lugar");
        ConGymBus = new ConfigGymBus();
        list = new ArrayList<ConfigurationGim>();
        loadConfigurationGym();
        searConfigurationGym(1);
    }

    public final void loadConfigurationGym() {

        String[] title = {"Codigo", "Nombre", "Dirección", "Teléfono"};
        modelo = new DefaultTableModel(null, title);
        String[] fila = new String[5];
        list = ConGymBus.list();

        for (ConfigurationGim c : list) {
            fila[0] = String.valueOf(c.getIdconfiguration());
            fila[1] = c.getNameGim();
            fila[2] = c.getAddress();
            fila[3] = c.getPhone();
            modelo.addRow(fila);
        }
        tbConfigurationGym.setModel(modelo);

    }

    public void asingConfigurationGym() {
        configurationGim = new ConfigurationGim();

        configurationGim.setIdconfiguration(Integer.parseInt(txtcodigo.getText()));
        configurationGim.setNameGim(txtgimnasio.getText());
        configurationGim.setAddress(txtaddress.getText());
        configurationGim.setPhone(txtphone.getText());

    }

    public void insertConfigurationGym() {
        String rpta;
        asingConfigurationGym();
        rpta = ConGymBus.insertConfigurationGym(configurationGim);
        if (rpta == null) {
            JOptionPane.showMessageDialog(null, "Se Ingreso el nuevo Gimnasio Correctamente");
        } else {
            JOptionPane.showMessageDialog(null, "Error al ingresar los datos");
        }
    }

    public void codConfigurationGym() {
        Integer id = ConGymBus.idConfigurationGym();
        txtcodigo.setText(String.valueOf(id));
    }

    public void searConfigurationGym(Integer id) {
        configurationGim = ConGymBus.get(id);
        if (configurationGim.getIdconfiguration() != null) {
            txtcodigo.setText(String.valueOf(configurationGim.getIdconfiguration()));
            txtgimnasio.setText(configurationGim.getNameGim());
            txtaddress.setText(configurationGim.getAddress());
            txtphone.setText(configurationGim.getPhone());
        } else {
            JOptionPane.showMessageDialog(null, "Gimnasio no Encontrado");
        }
    }

    public void deleteConfigurationGym() {
        Integer id = Integer.parseInt(txtcodigo.getText());
        String rpta = ConGymBus.delete(id);
        if (rpta == null) {
            JOptionPane.showMessageDialog(null, "Se eliminaron correctamente los datos ");
        } else {
            JOptionPane.showMessageDialog(null, "Error al eliminar los datos" + rpta);
        }
    }

    public void updateConfigurationGym() {
        asingConfigurationGym();
        String rpta = ConGymBus.update(configurationGim);
        if (null != rpta) {
            JOptionPane.showMessageDialog(null, "Error al Actualizar los datos");
        } else {
            JOptionPane.showMessageDialog(null, "Se Actualizarón los datos correctamente");
        }
    }

    public void clearEntry() {
        txtcodigo.setText(null);
        txtgimnasio.setText(null);
        txtaddress.setText(null);
        txtphone.setText(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnclose = new javax.swing.JButton();
        btnenabled = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtcodigo = new javax.swing.JTextPane();
        jButton6 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtgimnasio = new javax.swing.JTextPane();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtaddress = new javax.swing.JTextPane();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtphone = new javax.swing.JTextPane();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbConfigurationGym = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("/home/jose/Imágenes/Imagenes Java/config_gim.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 58));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uy/com/utu/gui/icono_save.png"))); // NOI18N
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btndelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uy/com/utu/gui/icono_close.png"))); // NOI18N
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        btnclose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uy/com/utu/gui/icono_close_1.png"))); // NOI18N
        btnclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncloseActionPerformed(evt);
            }
        });

        btnenabled.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uy/com/utu/gui/icono_nuevo.png"))); // NOI18N
        btnenabled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnenabledActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uy/com/utu/gui/icono_edit.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnenabled, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnclose, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(324, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnclose)
                    .addComponent(btndelete)
                    .addComponent(btnGuardar)
                    .addComponent(btnenabled)
                    .addComponent(jButton4))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 66, 620, 70));

        jLabel2.setText("Código");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 150, -1, 20));

        jScrollPane1.setViewportView(txtcodigo);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 70, -1));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uy/com/utu/gui/icono_search.png"))); // NOI18N
        jButton6.setPreferredSize(new java.awt.Dimension(64, 22));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 40, 25));

        jLabel3.setText("Nombre Gimnasio");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, -1, 20));

        jScrollPane2.setViewportView(txtgimnasio);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 290, -1));

        jLabel4.setText("Dirección");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, 20));

        jScrollPane3.setViewportView(txtaddress);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 230, -1));

        jLabel5.setText("Teléfono");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, -1, 20));

        jScrollPane4.setViewportView(txtphone);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, 240, -1));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 630, -1));

        tbConfigurationGym.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(tbConfigurationGym);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 630, 220));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try {
            if ((txtcodigo.getText().trim().isEmpty())&&(txtgimnasio.getText().trim().isEmpty())&&(txtaddress.getText().trim().isEmpty())&&(txtphone.getText().trim().isEmpty())) {
                if (option == true) {
                    insertConfigurationGym();
                } else {
                    updateConfigurationGym();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Los Campos no pueden ser nulos");
            }

            loadConfigurationGym();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error en el sistema" + e.getMessage());
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        deleteConfigurationGym();
        loadConfigurationGym();
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btncloseActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Integer id = Integer.valueOf(JOptionPane.showInputDialog("Ingrese Código Gimnasio"));
        searConfigurationGym(id);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void btnenabledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnenabledActionPerformed
        clearEntry();
        codConfigurationGym();
        option = true;

    }//GEN-LAST:event_btnenabledActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        option = false;
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLocationActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLocationActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLocationActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLocationActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLocationActivity().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnclose;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnenabled;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable tbConfigurationGym;
    private javax.swing.JTextPane txtaddress;
    private javax.swing.JTextPane txtcodigo;
    private javax.swing.JTextPane txtgimnasio;
    private javax.swing.JTextPane txtphone;
    // End of variables declaration//GEN-END:variables
}
